/**
 * background/license.js
 * License validation + cache for the Pro tier.
 *
 * Architecture rules:
 *   1. Free users never trigger a network call. fetchValidation() runs only
 *      when a key has been entered AND its 24-hour cache is stale.
 *   2. Background service worker owns the single source of truth (no popup
 *      writes here). Popups send LICENSE_* messages to background.
 *   3. 30-day offline grace: if the API is unreachable, the last known good
 *      result is honored for up to 30 days. After that, Pro features lock.
 *
 * Storage key (chrome.storage.local):
 *   smart_locator_license: {
 *     key, valid, tier, expiresAt, reason, checkedAt, networkOk
 *   }
 *
 * No imports — designed to be imported as an ES module from background.js
 * (which is already declared as `"type": "module"` in manifest.json).
 */

const LICENSE_KEY = "smart_locator_license";
const TRIAL_KEY = "smart_locator_trial";
const CACHE_TTL_MS = 24 * 60 * 60 * 1000;
const GRACE_MS = 30 * 24 * 60 * 60 * 1000;
const TRIAL_DURATION_MS = 7 * 24 * 60 * 60 * 1000;
const API_BASE = "https://api.smartselenium.dev"; // update if you bind a different domain

// Two accepted formats:
//   - Native SL- format generated by our worker: SL-XXXX-XXXX-XXXX
//   - LemonSqueezy UUID format issued by LS built-in License Keys feature
const KEY_PATTERN_SL   = /^SL-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}$/;
const KEY_PATTERN_UUID = /^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$/;
function isValidKeyFormat(k) {
  return KEY_PATTERN_SL.test(k) || KEY_PATTERN_UUID.test(k);
}

// Owner / founder bypass — recognized locally without a backend call so the
// founder can use Pro tier before the Cloudflare worker is deployed, and as
// a permanent dev key. Stored as SHA-256 so the real key never appears in
// the public source. Add more hashes for additional team members.
const OWNER_KEY_HASHES = new Set([
  "dce468205185b9fa5bea136cda60ff8a36d87edd78b330afffe20652da2f8f4e",
]);

async function sha256Hex(input) {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input));
  return Array.from(new Uint8Array(buf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

async function isOwnerKey(key) {
  if (!OWNER_KEY_HASHES.size) return false;
  const hash = await sha256Hex(key);
  return OWNER_KEY_HASHES.has(hash);
}

/* ---------------- Public API ---------------- */

/**
 * Validate + persist a freshly entered license key.
 * Returns the stored record (also written to chrome.storage.local).
 */
export async function setLicense(rawKey) {
  const key = String(rawKey || "").trim().toUpperCase();

  // Owner / founder bypass — skips network call, mirrors the $4.99/mo Pro tier
  // (tier=pro, 30-day rolling expiry) so the founder sees the same UX as paying
  // customers. Rolls forward every time the key is re-verified.
  if (await isOwnerKey(key)) {
    const rec = makeRecord({
      key, valid: true, tier: "pro",
      expiresAt: Date.now() + 30 * 24 * 60 * 60 * 1000,
      networkOk: true,
    });
    await chrome.storage.local.set({ [LICENSE_KEY]: rec });
    return rec;
  }

  if (!isValidKeyFormat(key)) {
    const rec = makeRecord({ key, valid: false, reason: "invalid-format" });
    await chrome.storage.local.set({ [LICENSE_KEY]: rec });
    return rec;
  }
  const res = await fetchValidation(key);
  const reason = res.networkOk === false
    ? (res.diag || "network-error")
    : (res.reason || null);
  const rec = makeRecord({
    key,
    valid: !!res.valid,
    tier: res.tier || null,
    expiresAt: res.expiresAt || null,
    reason,
    networkOk: res.networkOk !== false,
  });
  await chrome.storage.local.set({ [LICENSE_KEY]: rec });
  return rec;
}

/**
 * Force-refresh from the backend, bypassing the 24-hour cache.
 * Useful after a manual "Refresh license" button click in settings.
 */
export async function refreshLicense() {
  const stored = await chrome.storage.local.get(LICENSE_KEY);
  const cached = stored[LICENSE_KEY];
  if (!cached || !cached.key) return { valid: false, reason: "no-license" };
  return setLicense(cached.key);
}

/** Clear the license — for "Sign out" / "Remove license" in settings. */
export async function clearLicense() {
  await chrome.storage.local.remove(LICENSE_KEY);
  return { ok: true };
}

/** Returns the raw stored record (or null), without re-validating. */
export async function getLicenseRaw() {
  const stored = await chrome.storage.local.get(LICENSE_KEY);
  return stored[LICENSE_KEY] || null;
}

/**
 * Returns the current license status, refreshing from the backend if the
 * cached record is stale. Honors a 30-day offline grace window if the
 * backend is unreachable.
 */
export async function getLicenseStatus() {
  const cached = await getLicenseRaw();
  if (!cached || !cached.key) return { valid: false, reason: "no-license" };

  // Owner key: always valid, rolls expiry forward on each read so the founder
  // never gets locked out. Mirrors the $4.99/mo Pro tier UX.
  if (await isOwnerKey(cached.key)) {
    const needsRefresh = !cached.valid
      || !cached.expiresAt
      || cached.expiresAt < Date.now() + 7 * 24 * 60 * 60 * 1000;
    if (needsRefresh) {
      const rec = makeRecord({
        key: cached.key, valid: true, tier: "pro",
        expiresAt: Date.now() + 30 * 24 * 60 * 60 * 1000,
        networkOk: true,
      });
      await chrome.storage.local.set({ [LICENSE_KEY]: rec });
      return rec;
    }
    return cached;
  }

  const now = Date.now();
  // Fresh-enough cache: short-circuit, no network call
  if (cached.valid && cached.checkedAt && cached.checkedAt > now - CACHE_TTL_MS) {
    return cached;
  }

  // Cache stale → re-validate
  const res = await fetchValidation(cached.key);
  if (res.networkOk === false) {
    // Backend unreachable. Honor stale cache inside grace window.
    if (cached.valid && cached.checkedAt > now - GRACE_MS) {
      return { ...cached, fromGrace: true };
    }
    return {
      valid: false,
      reason: res.diag || "backend-unreachable",
      key: cached.key,
    };
  }

  const rec = makeRecord({
    key: cached.key,
    valid: !!res.valid,
    tier: res.tier || null,
    expiresAt: res.expiresAt || null,
    reason: res.reason || null,
    networkOk: true,
  });
  await chrome.storage.local.set({ [LICENSE_KEY]: rec });
  return rec;
}

/** Convenience wrapper for feature gates: true if license OR active trial. */
export async function isPro() {
  const s = await getLicenseStatus();
  if (s.valid === true && !!s.tier) return true;
  const t = await getTrialStatus();
  return t.active === true;
}

/* ---------------- Free 7-day trial ----------------
 * One-shot trial tracked in chrome.storage.sync (Google-account backed),
 * with chrome.storage.local as a fallback when sync is unavailable
 * (e.g. user signed out of Chrome).
 *
 * Why sync: uninstalling the extension wipes storage.local. If the trial
 * lived only in local storage, any user could reinstall and trigger the
 * trial again indefinitely. storage.sync persists to the user's Google
 * account, so reinstalls on the same profile carry the "used" flag
 * forward and survive Chrome reinstalls too.
 *
 * Bypass surface that still exists:
 *   - User signs out of Chrome before installing → no sync data → fresh trial
 *   - User uses a different Google account → fresh trial
 *   - Both sync + local cleared manually → fresh trial
 *
 * Acceptable for a $4.99 product. Server-side enforcement would require
 * email collection and is added in a later iteration once the worker
 * carries a /v1/trial/start endpoint.
 *
 * Storage record:
 *   smart_locator_trial: { startedAt, endsAt, used }
 */

async function readTrial() {
  // Prefer sync; fall back to local if sync unavailable
  try {
    const s = await chrome.storage.sync.get(TRIAL_KEY);
    if (s && s[TRIAL_KEY]) return s[TRIAL_KEY];
  } catch (_) { /* sync may be disabled */ }
  try {
    const l = await chrome.storage.local.get(TRIAL_KEY);
    return l[TRIAL_KEY] || null;
  } catch (_) {
    return null;
  }
}

async function writeTrial(rec) {
  // Write to both so we degrade gracefully if sync flips off later
  const payload = { [TRIAL_KEY]: rec };
  const writes = [];
  try { writes.push(chrome.storage.sync.set(payload)); } catch (_) {}
  try { writes.push(chrome.storage.local.set(payload)); } catch (_) {}
  await Promise.allSettled(writes);
}

export async function startTrial() {
  const cur = await getTrialStatus();
  if (cur.used) return { ok: false, reason: "already-used", ...cur };
  const now = Date.now();
  const rec = { startedAt: now, endsAt: now + TRIAL_DURATION_MS, used: true };
  await writeTrial(rec);
  return { ok: true, ...rec, active: true };
}

export async function getTrialStatus() {
  const t = await readTrial();
  if (!t || !t.startedAt) return { used: false, active: false };
  const now = Date.now();
  const active = t.endsAt > now;
  // Self-heal: if sync had it but local lost it (or vice versa), republish
  try { await writeTrial(t); } catch (_) {}
  return { ...t, active };
}

/* ---------------- Internals ---------------- */

function makeRecord(over) {
  return {
    key: over.key || null,
    valid: !!over.valid,
    tier: over.tier || null,
    expiresAt: over.expiresAt || null,
    reason: over.reason || null,
    checkedAt: Date.now(),
    networkOk: over.networkOk !== false,
  };
}

async function fetchValidation(key) {
  // Race the fetch against a 6s timeout so users don't sit on a stalled
  // popup when the backend is unreachable.
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 6000);
  try {
    const res = await fetch(`${API_BASE}/v1/license/validate`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ key }),
      signal: controller.signal,
    });
    clearTimeout(timeout);
    if (!res.ok) {
      return { valid: false, reason: `http-${res.status}`, networkOk: true };
    }
    const data = await res.json();
    return { ...data, networkOk: true };
  } catch (err) {
    clearTimeout(timeout);
    const msg = String((err && err.message) || err);
    // Distinguish "backend doesn't exist" from "user is offline"
    const isDnsOrConnect =
      err && (err.name === "AbortError"
        || /Failed to fetch|NetworkError|ERR_NAME_NOT_RESOLVED|ERR_CONNECTION/i.test(msg));
    console.warn("[SmartLocator] license fetch failed:", msg);
    return {
      networkOk: false,
      diag: isDnsOrConnect ? "backend-unreachable" : "network-error",
      diagMessage: msg,
    };
  }
}
