/**
 * Spectara — license API (Cloudflare Worker, Polar.sh backend)
 *
 * Routes:
 *   POST /v1/license/validate          — extension client
 *   POST /v1/webhook/polar             — Polar webhook (Standard Webhooks signed)
 *   GET  /v1/health                    — liveness probe
 *
 * Dependencies: zero. Uses Web Crypto + D1 binding only.
 *
 * Secrets (set with `wrangler secret put`):
 *   POLAR_WEBHOOK_SECRET               — Polar webhook signing secret
 *                                        (starts with `whsec_`, base64-encoded)
 *
 * Bindings (wrangler.toml):
 *   DB                                 — D1 database
 *
 * Polar license keys are UUID format: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
 * The extension's license.js accepts both this format and the legacy SL-
 * format from earlier dev builds.
 */

// Polar's license keys are UUIDs; we also accept legacy SL- keys generated by
// older worker builds so dev licenses keep working after the swap.
const KEY_PATTERN_UUID = /^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$/;
const KEY_PATTERN_SL = /^SL-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}$/;
const ALLOWED_TIERS = new Set(["pro", "team", "enterprise"]);

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const method = request.method;
    const path = url.pathname;

    if (method === "OPTIONS") return cors(new Response(null, { status: 204 }));

    try {
      if (method === "GET" && path === "/v1/health") {
        return cors(Response.json({ ok: true, ts: Date.now() }));
      }
      if (method === "POST" && path === "/v1/license/validate") {
        return cors(await handleValidate(request, env));
      }
      if (method === "POST" && path === "/v1/webhook/polar") {
        return await handlePolarWebhook(request, env); // no CORS on webhooks
      }
      return cors(new Response("Not Found", { status: 404 }));
    } catch (err) {
      console.error("worker error", err);
      return cors(Response.json({ error: "internal" }, { status: 500 }));
    }
  },
};

/* ------------------------------------------------------------------ */
/*  CORS                                                                */
/* ------------------------------------------------------------------ */
function cors(res) {
  const r = new Response(res.body, res);
  r.headers.set("Access-Control-Allow-Origin", "*");
  r.headers.set("Access-Control-Allow-Methods", "POST, GET, OPTIONS");
  r.headers.set("Access-Control-Allow-Headers", "content-type, webhook-id, webhook-timestamp, webhook-signature");
  r.headers.set("Access-Control-Max-Age", "86400");
  return r;
}

/* ------------------------------------------------------------------ */
/*  POST /v1/license/validate                                          */
/* ------------------------------------------------------------------ */
async function handleValidate(request, env) {
  let body;
  try {
    body = await request.json();
  } catch (_) {
    return Response.json({ valid: false, reason: "invalid-body" }, { status: 400 });
  }
  const key = String(body && body.key ? body.key : "").trim().toUpperCase();
  if (!KEY_PATTERN_UUID.test(key) && !KEY_PATTERN_SL.test(key)) {
    return Response.json({ valid: false, reason: "invalid-format" });
  }

  const row = await env.DB.prepare(
    "SELECT key, tier, status, expires_at FROM licenses WHERE key = ?"
  ).bind(key).first();

  if (!row) return Response.json({ valid: false, reason: "not-found" });
  if (row.status !== "active") {
    return Response.json({ valid: false, reason: row.status });
  }
  const now = Date.now();
  if (row.expires_at && row.expires_at < now) {
    await env.DB.prepare(
      "UPDATE licenses SET status = 'expired', updated_at = ? WHERE key = ?"
    ).bind(now, key).run();
    return Response.json({ valid: false, reason: "expired" });
  }

  try {
    await env.DB.prepare(
      "UPDATE licenses SET last_validated = ?, validations_count = validations_count + 1 WHERE key = ?"
    ).bind(now, key).run();
  } catch (e) {
    console.warn("counter update failed", e);
  }

  return Response.json({
    valid: true,
    tier: row.tier,
    expiresAt: row.expires_at,
  });
}

/* ------------------------------------------------------------------ */
/*  POST /v1/webhook/polar                                             */
/*  https://docs.polar.sh/integrate/webhooks                           */
/*  Polar uses the Standard Webhooks spec: standardwebhooks.com        */
/* ------------------------------------------------------------------ */
async function handlePolarWebhook(request, env) {
  const rawBody = await request.text();
  const ok = await verifyStandardWebhookSig(
    rawBody,
    request.headers,
    env.POLAR_WEBHOOK_SECRET,
  );
  if (!ok) return new Response("Bad signature", { status: 401 });

  let payload;
  try { payload = JSON.parse(rawBody); } catch (_) {
    return new Response("Bad JSON", { status: 400 });
  }
  const type = payload?.type;
  const data = payload?.data;
  if (!type || !data) return new Response("Missing event", { status: 400 });

  switch (type) {
    case "license_key.created":
    case "license_key.updated":
      await upsertFromLicenseKey(env, data);
      break;
    case "order.created":
      await upsertFromOrder(env, data);
      break;
    case "subscription.created":
    case "subscription.updated":
    case "subscription.active":
    case "subscription.uncanceled":
      await upsertFromSubscription(env, data);
      break;
    case "subscription.canceled":
    case "subscription.revoked":
      await markCancelledFromSubscription(env, data);
      break;
    default:
      // Unhandled event — ack 200 so Polar stops retrying
      break;
  }
  return new Response("ok");
}

/* ------------------------------------------------------------------ */
/*  Standard Webhooks signature (Polar uses this spec)                  */
/*                                                                      */
/*  Headers:                                                            */
/*    webhook-id          : unique event id                             */
/*    webhook-timestamp   : unix-second integer                         */
/*    webhook-signature   : space-separated "v1,<base64sig>" values     */
/*                                                                      */
/*  Signed content: `${id}.${timestamp}.${body}`                        */
/*  Secret: base64-encoded after the `whsec_` prefix                    */
/* ------------------------------------------------------------------ */
async function verifyStandardWebhookSig(rawBody, headers, secret) {
  if (!secret) return false;
  const id = headers.get("webhook-id");
  const ts = headers.get("webhook-timestamp");
  const sigHeader = headers.get("webhook-signature");
  if (!id || !ts || !sigHeader) return false;

  // Reject replays older than 5 minutes
  const tsNum = parseInt(ts, 10);
  if (!Number.isFinite(tsNum)) return false;
  const nowSec = Math.floor(Date.now() / 1000);
  if (Math.abs(nowSec - tsNum) > 300) return false;

  const secretClean = secret.replace(/^whsec_/, "");
  const secretBytes = base64ToBytes(secretClean);
  const signedContent = `${id}.${ts}.${rawBody}`;

  const key = await crypto.subtle.importKey(
    "raw",
    secretBytes,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sigBuf = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(signedContent));
  const expected = bytesToBase64(new Uint8Array(sigBuf));

  // sigHeader: "v1,<sig1> v1,<sig2>"  (space-separated for key rotation)
  const candidates = sigHeader.split(" ")
    .map((s) => s.trim())
    .filter((s) => s.startsWith("v1,"))
    .map((s) => s.slice(3));

  return candidates.some((c) => timingSafeEqualStr(c, expected));
}

function base64ToBytes(b64) {
  const bin = atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  return arr;
}
function bytesToBase64(bytes) {
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
}
function timingSafeEqualStr(a, b) {
  if (a.length !== b.length) return false;
  let mismatch = 0;
  for (let i = 0; i < a.length; i++) {
    mismatch |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return mismatch === 0;
}

/* ------------------------------------------------------------------ */
/*  Webhook → DB writes                                                */
/* ------------------------------------------------------------------ */

/**
 * Polar's native license_key feature emits this when a license is granted
 * (after order checkout completes). This is the primary code path —
 * customers paste the Polar-issued key into the extension.
 */
async function upsertFromLicenseKey(env, lk) {
  const key = String(lk.key || "").trim().toUpperCase();
  if (!key) return;
  const email = String(lk?.customer?.email || lk?.user?.email || "").toLowerCase();
  const polarLicenseId = String(lk.id || "");
  const status = (lk.status === "granted" || lk.status === "active") ? "active" : "cancelled";

  // Expiry: license_keys can be tied to a subscription. Polar doesn't always
  // send expires_at on license_key.created — subscription.updated webhook
  // fills it in. Default to NULL (treat as active until subscription says
  // otherwise).
  const expires_at = lk.expires_at ? Date.parse(lk.expires_at) : null;
  const now = Date.now();
  const tier = inferTier(lk);

  const existing = await env.DB.prepare(
    "SELECT key FROM licenses WHERE polar_license_key_id = ? OR key = ?"
  ).bind(polarLicenseId, key).first();

  if (existing) {
    await env.DB.prepare(
      `UPDATE licenses
         SET key = ?, email = COALESCE(?, email), tier = ?, status = ?,
             expires_at = COALESCE(?, expires_at), updated_at = ?,
             polar_license_key_id = ?
       WHERE key = ?`
    ).bind(key, email || null, tier, status, expires_at, now, polarLicenseId, existing.key).run();
  } else {
    await env.DB.prepare(
      `INSERT INTO licenses
         (key, email, tier, status, expires_at, created_at, updated_at,
          polar_license_key_id)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
    ).bind(key, email, tier, status, expires_at, now, now, polarLicenseId).run();
  }
}

/**
 * Order.created fires before license_key.created. We use it to record
 * polar_order_id linkage in case the license_key event arrives later or
 * is replayed. License row is created/updated when license_key fires.
 */
async function upsertFromOrder(env, order) {
  // For products without license_keys enabled, generate our own SL- key
  // and treat order as a lifetime purchase. With license_keys enabled
  // (recommended), this is a no-op — license_key.created handles it.
  const hasLicenseFeature = !!(order.product?.has_license_key || order.product?.benefits?.some?.((b) => b.type === "license_keys"));
  if (hasLicenseFeature) return;

  const email = String(order?.customer?.email || "").toLowerCase();
  const orderId = String(order.id || "");
  const tier = inferTier(order);
  if (!ALLOWED_TIERS.has(tier)) return;

  const existing = await env.DB.prepare(
    "SELECT key FROM licenses WHERE polar_order_id = ?"
  ).bind(orderId).first();
  if (existing) return;

  const key = generateLicenseKey();
  const now = Date.now();
  await env.DB.prepare(
    `INSERT INTO licenses
       (key, email, tier, status, expires_at, created_at, updated_at, polar_order_id)
     VALUES (?, ?, ?, 'active', NULL, ?, ?, ?)`
  ).bind(key, email, tier, now, now, orderId).run();
}

async function upsertFromSubscription(env, sub) {
  const subId = String(sub.id || "");
  const email = String(sub?.customer?.email || sub?.user?.email || "").toLowerCase();
  const tier = inferTier(sub);
  if (!ALLOWED_TIERS.has(tier)) return;

  // Polar typically sends current_period_end (ISO string) or ends_at on cancel.
  const endsAtStr = sub.current_period_end || sub.ends_at || null;
  const expires_at = endsAtStr ? Date.parse(endsAtStr) : null;
  const now = Date.now();

  await env.DB.prepare(
    `UPDATE licenses
       SET status = 'active', tier = ?, expires_at = ?, updated_at = ?,
           polar_subscription_id = ?
     WHERE polar_subscription_id = ?
        OR polar_order_id = ?`
  ).bind(tier, expires_at, now, subId, subId, sub.order_id || "").run();

  // If no row matched (subscription created without prior license), create one
  const existing = await env.DB.prepare(
    "SELECT key FROM licenses WHERE polar_subscription_id = ?"
  ).bind(subId).first();
  if (!existing) {
    const key = generateLicenseKey();
    await env.DB.prepare(
      `INSERT INTO licenses
         (key, email, tier, status, expires_at, created_at, updated_at, polar_subscription_id)
       VALUES (?, ?, ?, 'active', ?, ?, ?, ?)`
    ).bind(key, email, tier, expires_at, now, now, subId).run();
  }
}

async function markCancelledFromSubscription(env, sub) {
  const subId = String(sub.id || "");
  const now = Date.now();
  await env.DB.prepare(
    "UPDATE licenses SET status = 'cancelled', updated_at = ? WHERE polar_subscription_id = ?"
  ).bind(now, subId).run();
}

/* ------------------------------------------------------------------ */
/*  Tier inference                                                      */
/*  Polar attaches metadata to product / variant. Set                   */
/*    metadata: { tier: "pro" }                                         */
/*  on each variant in Polar dashboard for explicit control.            */
/* ------------------------------------------------------------------ */
function inferTier(obj) {
  const explicit = obj?.metadata?.tier
    || obj?.product?.metadata?.tier
    || obj?.subscription?.metadata?.tier;
  if (explicit && ALLOWED_TIERS.has(explicit)) return explicit;

  const name = String(
    obj?.product?.name
    || obj?.product_name
    || obj?.subscription?.product?.name
    || ""
  ).toLowerCase();
  if (name.includes("enterprise")) return "enterprise";
  if (name.includes("team")) return "team";
  return "pro";
}

/* ------------------------------------------------------------------ */
/*  Fallback SL- key generator (when Polar license keys are NOT used)   */
/* ------------------------------------------------------------------ */
const KEY_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
function generateLicenseKey() {
  const block = () => {
    const buf = crypto.getRandomValues(new Uint8Array(4));
    return Array.from(buf, (b) => KEY_ALPHABET[b % KEY_ALPHABET.length]).join("");
  };
  return `SL-${block()}-${block()}-${block()}`;
}
